### ISSUE TITLE
roll dice to preselected value

### ISSUE THREAD

**Issue by rdewolff** [emanchado/3d-die-roller#1]
Hi!

Am wondering if we could add a function to roll dices to a preselected value?

That'd allow us, for example, to have 1 player roll the dice randomly, and the other players watching him see the dices rolled and the result would be the same for everyone.

Any idea how to accomplish that with your 3d-die-roller lib version?

**Comment by emanchado** [comment]
Hm, I'm not sure I understand the request. When you say "other players", are you implying "in their own computers", as in when playing online?

If I understand your request, I don't think it's easy :-( Most of the code is actually not written by me (see README), but I have the impression that it uses actual physics simulation and then it figures out what side is up...

**Comment by emanchado** [comment]
Ok, I'll close this old issue.
