### ISSUE TITLE
Shadows seem to be cropped/missing at an angle right of center

### ISSUE THREAD

**Issue by MillerMark** [emanchado/3d-die-roller#2]
Shadows seem to be cropped along a diagonal line, slightly right of center. For example, in the screenshot below, you can only see shadows for 4 of the 7 dice, and the shadow for the 4th die is cropped by a sharp diagonal line.

![image](https://user-images.githubusercontent.com/4841528/50899819-e0fc3700-13d8-11e9-8278-e2db793d6434.png)

**Comment by emanchado** [comment]
I'm afraid I know nothing about 3D, I don't even know where to start :cry: 
This code is not written by me originally, it's a copy of the code http://www.teall.info/2014/01/online-3d-dice-roller.html, then refactored and cleaned up somewhat to make it easier to work with.

So I'm tempted to just close it, or maybe contact the original author. Unless you have any ideas or can prepare a patch?

**Comment by MillerMark** [comment]
This change appears to fix the issue for me:

light.shadowCameraFar = mw * 4;
